version: '3'
services:
  mage:
    build:
      context: .
      dockerfile: mage.dockerfile
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src
    command: mage start homework_03
  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/home/mlflow_data/
    networks:
      - default
